// packages/solid/src/useEdgeEffect.ts
import { createEffect, onCleanup } from 'solid-js';
import { graph as defaultGraph } from '@veriscope/graph';
import type { CircuitGraph, Signal, ReadonlySignal } from '@veriscope/graph';

interface UseEdgeEffectOptions {
  graph?: CircuitGraph;
}

/**
 * Fire an action on a signal edge transition (posedge or negedge).
 * Wraps Solid's createEffect with edge detection and graph instrumentation.
 *
 * - posedge: fires when the signal transitions from falsy to truthy
 * - negedge: fires when the signal transitions from truthy to falsy
 */
export function useEdgeEffect(
  signal: Signal<any> | ReadonlySignal<any>,
  edge: 'posedge' | 'negedge',
  action: () => void,
  name: string,
  options?: UseEdgeEffectOptions,
): void {
  const g = options?.graph ?? defaultGraph;

  const nodeId = g.registerNode({
    name,
    type: 'effect',
    deps: [signal.nodeId],
  });

  let prev: any = signal.val;
  let initialized = false;

  createEffect(() => {
    const current = signal.val;

    if (!initialized) {
      initialized = true;
      prev = current;
      return;
    }

    let edgeDetected = false;
    if (edge === 'posedge') {
      edgeDetected = !prev && !!current;
    } else {
      edgeDetected = !!prev && !current;
    }

    prev = current;

    if (edgeDetected) {
      g.notifyEffect(nodeId);
      action();
    }
  });

  onCleanup(() => g.disposeNode(nodeId));
}

// packages/react/src/useEdgeEffect.ts
import { useEffect, useRef } from 'react';
import { graph as defaultGraph } from '@veriscope/graph';
import type { Signal, ReadonlySignal, CircuitGraph } from '@veriscope/graph';

interface UseEdgeEffectOptions {
  graph?: CircuitGraph;
}

/**
 * Fire an action on a signal edge transition (posedge or negedge).
 *
 * - posedge: fires when the signal transitions from falsy to truthy
 * - negedge: fires when the signal transitions from truthy to falsy
 *
 * Registers the effect in the CircuitGraph.
 */
export function useEdgeEffect(
  signal: Signal<any> | ReadonlySignal<any>,
  edge: 'posedge' | 'negedge',
  action: () => void,
  name: string,
  options?: UseEdgeEffectOptions,
): void {
  const g = options?.graph ?? defaultGraph;
  const nodeIdRef = useRef<string | null>(null);
  const prevRef = useRef<any>(signal.val);
  const initializedRef = useRef(false);
  const graphRef = useRef(g);

  // Register in graph once
  if (nodeIdRef.current === null) {
    nodeIdRef.current = graphRef.current.registerNode({
      name,
      type: 'effect',
      deps: [signal.nodeId],
    });
  }

  const nodeId = nodeIdRef.current;
  const currentVal = signal.val;

  useEffect(() => {
    // Skip the initial render — we only care about transitions
    if (!initializedRef.current) {
      initializedRef.current = true;
      prevRef.current = currentVal;
      return;
    }

    const prev = prevRef.current;
    prevRef.current = currentVal;

    let edgeDetected = false;
    if (edge === 'posedge') {
      edgeDetected = !prev && !!currentVal;
    } else {
      edgeDetected = !!prev && !currentVal;
    }

    if (edgeDetected) {
      graphRef.current.notifyEffect(nodeId);
      action();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentVal]);

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      if (nodeIdRef.current) {
        graphRef.current.disposeNode(nodeIdRef.current);
      }
    };
  }, []);
}
