// packages/react/src/useTrackedEffect.ts
import { useEffect, useRef } from 'react';
import { graph as defaultGraph } from '@veriscope/graph';
import type { Signal, ReadonlySignal, CircuitGraph } from '@veriscope/graph';

interface UseTrackedEffectOptions {
  graph?: CircuitGraph;
}

/**
 * Run a tracked side effect whenever any of the given signals change.
 * Registers the effect in the CircuitGraph with edges from each dependency.
 * The effect function can optionally return a cleanup function.
 */
export function useTrackedEffect(
  fn: () => void | (() => void),
  deps: Array<Signal<any> | ReadonlySignal<any>>,
  name: string,
  options?: UseTrackedEffectOptions,
): void {
  const g = options?.graph ?? defaultGraph;
  const nodeIdRef = useRef<string | null>(null);
  const graphRef = useRef(g);

  // Register in graph once
  if (nodeIdRef.current === null) {
    nodeIdRef.current = graphRef.current.registerNode({
      name,
      type: 'effect',
      deps: deps.map(d => d.nodeId),
    });
  }

  const nodeId = nodeIdRef.current;

  // Extract .val from each dep so React's useEffect tracks them
  const depValues = deps.map(d => d.val);

  useEffect(() => {
    graphRef.current.notifyEffect(nodeId);
    const cleanup = fn();
    return cleanup ?? undefined;
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, depValues);

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      if (nodeIdRef.current) {
        graphRef.current.disposeNode(nodeIdRef.current);
      }
    };
  }, []);
}

// packages/solid/src/useTrackedEffect.ts
import { createEffect, onCleanup } from 'solid-js';
import { graph as defaultGraph } from '@veriscope/graph';
import type { CircuitGraph, Signal, ReadonlySignal } from '@veriscope/graph';

interface UseTrackedEffectOptions {
  graph?: CircuitGraph;
}

/**
 * Run a tracked side effect whenever any of the given signals change.
 * Wraps Solid's createEffect with graph instrumentation.
 */
export function useTrackedEffect(
  fn: () => void | (() => void),
  deps: Array<Signal<any> | ReadonlySignal<any>>,
  name: string,
  options?: UseTrackedEffectOptions,
): void {
  const g = options?.graph ?? defaultGraph;

  const nodeId = g.registerNode({
    name,
    type: 'effect',
    deps: deps.map(d => d.nodeId),
  });

  let cleanup: (() => void) | void;

  createEffect(() => {
    // Read all deps to establish Solid's tracking
    deps.forEach(d => d.val);

    // Run previous cleanup
    if (typeof cleanup === 'function') cleanup();

    g.notifyEffect(nodeId);
    cleanup = fn();
  });

  onCleanup(() => {
    if (typeof cleanup === 'function') cleanup();
    g.disposeNode(nodeId);
  });
}
